# -*- coding: utf-8 -*-
"""gen_ai_rag_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5ZGldFFJZaAiFFermaQ7dM9E9B-cYYq
"""

!pip install sentence-transformers

!pip install PyMuPDF

import fitz     #PyMuPDF
from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
#sentence embedding model, good at checking similarity between short text (query vs paragraph)

#function to extract text from uploaded PDF
def extract_data_from_pdf(pdf_path):
  doc = fitz.open(pdf_path)
  full_text = ""
  for page in doc:
    text = page.get_text()
    full_text += text
  return full_text

text = """
Company Manual - TechNova Solutions Pvt. Ltd. About the Company TechNova Solutions Pvt. Ltd. is a global leader in consumer electronics,
committed to delivering innovative technology and excellent customer service. Founded in 2005, TechNova has grown to serve over 20 million
customers across 35 countries. We specialize in smart devices, home automation, and sustainable technology solutions.
Our mission is to make everyday life smarter, simpler, and more connected. We believe in constant innovation, environmental responsibility,
and customer satisfaction above all else. Our headquarters are located in Bengaluru, India, with major regional offices in Singapore, Germany,
and the United States. Return Policy We offer a 30-day return policy on all our products purchased directly through our website or authorized outlets.
To be eligible for a return, the product must be unused, in its original packaging, and accompanied by the original invoice.
Refunds are initiated after we receive and inspect the returned item.
"""

len(text.split())

text_splited = text.split()
' '.join(text_splited[0:0+20])

for i in range(0,10,3):
  print(i)

#function to split text text into sentences/chunks

def split_into_sentences(text, chunk_size = 500):
  sentences = text.split()
  sections = []
  for i in range(0 , len(sentences) , chunk_size):
    section = ' '.join(sentences[i : i+chunk_size])
    sections.append(section)
  return sections



