# -*- coding: utf-8 -*-
"""gen_ai_diffusion_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCMqSYzcp6IEV_UFXN4trTCl1__SnVlK

**Diffusion Model**
"""

!pip install diffusers transformers

from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
from IPython.display import Image,display

#Load model or stable diffusion
#pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16).to("cuda")

from diffusers import StableDiffusion3Pipeline
#model_id = "sd-legacy/stable-diffusion-v1-5"
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

#prompt = "A cinematic image of a Lion wearing sunglasses in a desert at sunset"

prompt = "A HD image of a Man fashion model wearing black suit"
image = pipe(prompt , guidance_scale=2).images[0]

image.save('generated_image.png')

import cv2
image_read = cv2.imread('/content/generated_image.png')
image_read = cv2.cvtColor(image_read , cv2.COLOR_BGR2RGB)
image_read



import matplotlib.pyplot as plt
plt.imshow(image)
plt.show()

!pip install gradio

import gradio as gr
def generate_image(prompt):
  image = pipe(prompt , guidance_scale=2).images[0]
  return image

gr.Interface(fn=generate_image , inputs="text" , outputs="image" , title="Image Generator").launch()

from huggingface_hub import notebook_login

notebook_login()

import torch
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3.5-large", torch_dtype=torch.bfloat16)
pipe = pipe.to("cuda")

image = pipe(
    "A capybara holding a sign that reads Hello World",
    num_inference_steps=28,
    guidance_scale=3.5,
).images[0]
image.save("capybara.png")

import cv2
image_read = cv2.imread('/content/capybara.png')
image_read = cv2.cvtColor(image_read , cv2.COLOR_BGR2RGB)
image_read



